# Generated by Django 2.2 on 2024-03-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0004_auto_20240320_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
