# Generated by Django 2.2 on 2024-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0005_auto_20240320_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='images/2111.w039.n003.5B.p1.5.jpg', upload_to=''),
        ),
    ]
