# Generated by Django 2.2 on 2024-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0006_auto_20240320_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to='ftp/images'),
        ),
    ]
