# Generated by Django 2.2 on 2024-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0007_auto_20240320_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
