# Generated by Django 2.2 on 2024-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0008_trainingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkExpansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
