# Generated by Django 2.2 on 2024-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0009_networkexpansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkexpansion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='network_images/'),
        ),
    ]
