# Generated by Django 2.2 on 2024-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0013_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='2111.w039.n003.5B.p1.5.jpg', upload_to='game_images/'),
        ),
    ]
